require 'waddup/event'
require 'waddup/registry'
require 'waddup/source'
require 'waddup/sources/apple_calender'
require 'waddup/sources/apple_mail'
require 'waddup/sources/git'
require 'waddup/version'
